name = input("Name: ")
age = input("Age: ")
favorite_color = input("Favorite Color: ")
favorite_movie = input("Favorite Movie: ")
mobile_number = input("Mobile Number: ")
motto = input("Motto in Life: ")

print("Hi " + name + "!")
print("You're " + age + " years old")
print("Your favorite color is " + favorite_color)
print("Your favorite movie is " + favorite_movie)
print("Your mobile number is " + mobile_number)
print("Your motto in life is: ")
print(motto)
